# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=10, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('i2c_address', models.CharField(blank=True, max_length=10, null=True)),
                ('firmware_version', models.IntegerField(blank=True, null=True)),
                ('dc_voltage', models.CharField(blank=True, max_length=10, null=True)),
                ('dc_current', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_1', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_2', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_3', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_4', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_5', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_6', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_7', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_8', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_9', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_min', models.CharField(blank=True, max_length=10, null=True)),
                ('cv_max', models.CharField(blank=True, max_length=10, null=True)),
                ('mosfet_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('pack_temp', models.CharField(blank=True, max_length=10, null=True)),
                ('cell_overvoltage_level_1', models.CharField(blank=True, max_length=10, null=True)),
                ('cell_overvoltage_level_2', models.CharField(blank=True, max_length=10, null=True)),
                ('cell_undervoltage_level_1', models.CharField(blank=True, max_length=10, null=True)),
                ('cell_undervoltage_level_2', models.CharField(blank=True, max_length=10, null=True)),
                ('pack_overcurrent', models.CharField(blank=True, max_length=10, null=True)),
                ('pack_overtemperature_mosfet', models.CharField(blank=True, max_length=10, null=True)),
                ('pack_overtemperature_cells', models.CharField(blank=True, max_length=10, null=True)),
                ('is_on', models.BooleanField(default=False)),
                ('error_flag', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, choices=[('UNDER TEST', 'UNDER TEST'), ('FREE', 'FREE'), ('OFFLINE', 'OFFLINE')], max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('ve_bus_address', models.CharField(blank=True, max_length=10, null=True)),
                ('dc_current', models.CharField(blank=True, max_length=10, null=True)),
                ('dc_voltage', models.CharField(blank=True, max_length=10, null=True)),
                ('ac_current', models.CharField(blank=True, max_length=10, null=True)),
                ('ac_voltage', models.CharField(blank=True, max_length=10, null=True)),
                ('setpoint', models.CharField(blank=True, max_length=10, null=True)),
                ('is_on', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('FREE', 'FREE'), ('BUSY', 'BUSY'), ('OFFLINE', 'OFFLINE')], default='OFFLINE', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='InverterPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('result', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
                ('config', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(choices=[('RUNNING', 'RUNNING'), ('STOPPED', 'STOPPED'), ('FAILED', 'FAILED'), ('FINISHED', 'FINISHED'), ('PENDING', 'PENDING')], default='PENDING', max_length=32)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='base.Battery')),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='base.Inverter')),
            ],
        ),
        migrations.AddField(
            model_name='inverter',
            name='inverter_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverters', related_query_name='inverters', to='base.InverterPool'),
        ),
    ]
