# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('ve_bus_address', models.CharField(blank=True, max_length=10, null=True)),
                ('dc_current', models.CharField(blank=True, max_length=10, null=True)),
                ('dc_voltage', models.CharField(blank=True, max_length=10, null=True)),
                ('ac_current', models.CharField(blank=True, max_length=10, null=True)),
                ('ac_voltage', models.CharField(blank=True, max_length=10, null=True)),
                ('setpoint', models.CharField(blank=True, max_length=10, null=True)),
                ('is_on', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('FREE', 'FREE'), ('BUSY', 'BUSY'), ('OFFLINE', 'OFFLINE')], default='OFFLINE', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='InverterPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_available_inverters', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='battery',
            name='cell_overvoltage_level_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cell_overvoltage_level_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cell_undervoltage_level_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cell_undervoltage_level_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_7',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_8',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_9',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_max',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='cv_min',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='dc_current',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='dc_voltage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='error_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battery',
            name='firmware_version',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='i2c_address',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battery',
            name='mosfet_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='pack_overcurrent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='pack_overtemperature_cells',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='pack_overtemperature_mosfet',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='pack_temp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='port',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='serial_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inverter',
            name='inverter_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverters', related_query_name='inverters', to='base.InverterPool'),
        ),
    ]
