# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=32, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='base.TestCase')),
            ],
        ),
    ]
