# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
