# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171215_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inverterpool',
            name='nr_available_inverters',
        ),
    ]
