# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-17 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20171217_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='inverter',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='inverterpool',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
