# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180108_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='cell_overvoltage_level_1',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='battery',
            name='cell_overvoltage_level_2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='battery',
            name='cell_undervoltage_level_1',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='battery',
            name='cell_undervoltage_level_2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='battery',
            name='pack_overcurrent',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='battery',
            name='pack_overtemperature_cells',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='battery',
            name='pack_overtemperature_mosfet',
            field=models.NullBooleanField(),
        ),
    ]
