# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-10 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180109_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='dc_capacity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inverter',
            name='dc_energy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
