# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180110_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['timestamp']},
        ),
    ]
