# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180111_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='graph',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
