# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20180111_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
