# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180111_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='date_created',
            new_name='created',
        ),
        migrations.AddField(
            model_name='testcase',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
