# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-11 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20180111_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='graph',
            field=models.CharField(blank=True, default='#', max_length=128, null=True),
        ),
    ]
