# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180111_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('CHARGE', 'CHARGE'), ('REST', 'REST'), ('DISCHARGE', 'DISCHARGE'), ('STOP', 'STOP')], max_length=32, null=True)),
                ('trigger', models.CharField(blank=True, choices=[('RECIPE', 'RECIPE'), ('SAFETY_CHECK_L1', 'SAFETY_CHECK_L1'), ('SAFETY_CHECK_L2', 'SAFETY_CHECK_L2'), ('ERROR', 'ERROR')], help_text='safety_check_l1|safety_check_l2', max_length=128, null=True)),
                ('message', models.CharField(blank=True, help_text='overvoltage on ...|undervoltage on ...', max_length=128, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='recipe',
            field=models.CharField(default='/Users/mihaidobre/PycharmProjects/source/battery_tester/src/backend/settings/test_recipe.csv', max_length=64),
        ),
        migrations.AddField(
            model_name='testcaseevent',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_event', to='base.TestCase'),
        ),
    ]
