# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20180117_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='port',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='dc_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='dc_energy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='port',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
