# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20180129_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inverter',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='recipe',
            field=models.CharField(default='/home/razvan/eclipse-workspace/battery_tester/src/backend/settings/test_recipe.csv', max_length=128),
        ),
    ]
